.\" Manpage for interject.
.TH INTERJECT "1" "April 2019" "interject 1.0.0" "User Commands"
.SH NAME
interject \- Inspect and edit the contents of a pipe
.SH SYNOPSIS
command1 | interject [-s] [-e EDITOR] [-t TEMPDIR] | command2
.SH DESCRIPTION
.B interject(1)
is a tool for inspecting the contents of a pipe with an editor.
This is particularly useful in the case where you plan on piping a script retrieved by
.BR curl(1)
into a shell directly.
.B interject(1)
is an alternative to
.BR vipe(1)
that allows the user to control the tool with flags, in addition to environment variables.
.SH ENVIRONMENT VARIABLES
.TP
.B EDITOR
If the
.B \-e
option is not used,
.B interject(1)
will use the editor set in this environment variable.
If the variable is unset,
.B interject(1)
will default to using
.BR vim(1)
.PP
.TP
.B TEMPDIR
If the
.B \-t
option is not  used,
.B interject(1)
will use a temporary directory set in this environment variable.
If the variable is unset, the temporary directory used will default to
.I /tmp
.SH OPTIONS
.TP
.BR \-s
Use
.BR sponge(1)
to drain the pipe before attempting to open it in the editor.
.PP
.TP
.BR \-e " " EDITOR
Set the editor used to view the pipe to \fBEDITOR\fP.
.PP
.TP
.BR \-t " " TEMPDIR
Set the temporary directory used by
.B interject(1)
to \fBTEMPDIR\fP.
.SH EXAMPLES
.TP
command1 | interject -e emacs | command2
Pipe the contents of \fBcommand1\fP into a temporary file, then read that file with \fBemacs\fP; if \fBemacs\fP closes without an error code, pipe the input into \fBcommand2\fP.
command1 | interject -t /temp_dir | command2
Use the temporary directory \fI/temp_dir/\fP instead of \fI/tmp/\fP or \fBTEMPDIR\fP.
curl www.example.com | interject -s | bash
Use \fBsponge\fP to capture the entire output of \fBcurl\fP, then edit it in the default \fBEDITOR\fP; if there are no problems, run the pipe as a script using \fBbash\fP.
interject -h
Display the usage info for \fBinterject(1)\fP.
.SH SEE ALSO
.BR vipe(1)
.SH AUTHOR
Elliott Indiran <elliott.indiran@protonmail.com>
.SH BUGS
Report bugs here: \fIhttps://github.com/eindiran/interject\fP
.SH COPYRIGHT
Copyright © 2019 Elliott Indiran.
License: MIT <https://mit-license.org/>
This is free software: you are free to make changes to it for any purpose.
There is \fBNO WARRANTY\fP, to the extent permitted by law.
